name: build-in-pipeline-post

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["build-in-docker"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

